CREATE TABLE shedlock
(
  name       VARCHAR(64)  NOT NULL,
  lock_until DATETIME     NULL,
  locked_at  DATETIME     NULL,
  locked_by  VARCHAR(255) NOT NULL,
  PRIMARY KEY (name)
);

CREATE TABLE DOMAIN_EVENT
(
  ID            VARCHAR(32) NOT NULL,
  JSON_CONTENT  JSON        NOT NULL,
  TYPE          VARCHAR(100) GENERATED ALWAYS AS (JSON_CONTENT ->> '$._type') VIRTUAL,
  CREATED_AT    BIGINT GENERATED ALWAYS AS (JSON_CONTENT ->> '$._createdAt') VIRTUAL,
  PUBLISH_TRIES INT DEFAULT 0,
  PRIMARY KEY (ID)
) CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE DOMAIN_EVENT_RECEIVE_RECORD
(
  EVENT_ID    CHAR(32) NOT NULL,
  RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_ID)
) CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
